version: "3.8"
services:
  app:
    build: ./docker/php
    volumes:
      - ./src:/work
  web:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./src:/work
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DATABASE: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 15432:5432

  redis:
    image: redis:alpine
    ports: 
      - 16379:6379
